### ISSUE TITLE
Why the replace '_' with " "?

### ISSUE THREAD

**Issue by rwightman** [facebookresearch/imagenetx#3] opened 2022-11-29 05:57 UTC
Is there a reason why _ is replaced with space in the plotting code? 

It makes some indexing ops (ie setting a hue based on a different model name ordering) if you have model names with underscores rather challenging, it also doesn't necessarily improve aesthetics so seems like it should at least be optional unless there is some technical reason I'm missing?

**Comment by BadrYoubiIdrissi** [comment] 2022-11-29 08:16
When using the --use-tex option in the plotting code, keeping the _ raises an error if I recall correctly. But I agree that it is incovenient!

**Comment by rwightman** [comment] 2022-11-29 08:52
@BadrYoubiIdrissi would you consider a PR if I added a bool flag to disable that, esp for the `model_comparison` fn. I've been fiddling with imagenet-x comparing some recent / past models and ended up just hacking the code to make it work for now...

See use in here, I import ver of the compare with that replace removed:
https://colab.research.google.com/drive/12u1csH7_Uun78lGti35zvi5-S6FX4ZKu?usp=sharing

**Comment by BadrYoubiIdrissi** [comment] 2022-11-29 08:59
Of course ! Feel free to open a pull request for anything that would make using the code easier. I can spare you the trouble for this one though, it's an easy fix.

**Comment by BadrYoubiIdrissi** [comment] 2022-11-29 09:20
@rwightman It should now be fixed. You can upgrade to 0.0.7 and specify remove_underscore=False in the call to model_comparison. Feel free to close the issue if the problem is solved. Thank you for sharing the google colab ! Those are very interesting results !

**Comment by rwightman** [comment] 2022-11-29 21:35
@BadrYoubiIdrissi great, thanks, switched that notebook to use it and tested so will close this now

**Closed as completed** 2022-11-29 21:35 UTC
